---
- name: setup Java and tomcat server
  hosts: all
  become: true
  vars:
    - tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.93/bin/apache-tomcat-8.5.93.tar.gz
    - tomcat_package: apache-tomcat-8.5.93
  tasks:
   - name: Update apt cache (for Ubuntu/Debian)
     apt:
       update_cache : yes
     when: ansible_os_family == "Debian"  # Only execute on Debian-based systems

   - name: install java 1.8
     apt:
       name: openjdk-8-jdk 
       state: present

   - name: Download Tomcat server package
     get_url:
       url: "{{ tomcat_url }}" # put var. in double quotes in case the var. is in starting of the line 
       dest: /usr/local

   - name: Extract Tomcat Package
     unarchive: 
       src: /usr/local/{{tomcat_package}}.tar.gz
       dest: /usr/local/
       remote_src: yes

   - name: Start tomcat services
     shell: nohup /usr/local/{{tomcat_package}}/bin/startup.sh #nohup -start the service in background if you log off from server         
